FROM nkl322/django-pet-frontend as frontend-build
FROM nkl322/django-pet-backend as backend-build
FROM nginx:alpine as prod
RUN mkdir -p /var/lib/nginx/tmp && \
    chown -R nginx:nginx /var/cache/nginx /usr/share/nginx/html /var/lib/nginx
COPY --from=frontend-build /home/nkl/frontend/dist/frontend /usr/share/nginx/html
COPY --from=backend-build /home/nkl/backend/staticfiles /static
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
USER nginx
ENTRYPOINT ["nginx", "-g", "daemon off;"]
